version: '3.8'

services:
  arangodb:
    image: arangodb:latest
    ports:
      - "8529:8529"
    environment:
      ARANGO_ROOT_PASSWORD: "testpassword"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8529/_db/_system/_admin/aardvark/index.html"]
      interval: 30s
      timeout: 10s
      retries: 5
