name: Manual Build & Push

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Array of platforms for which the Docker image should be built.'
        required: false
        default: '[ "linux/amd64", "linux/arm64/v8" ]' # Default as JSON array

env:
  REGISTRY_IMAGE: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: ${{ fromJson(inputs.platforms) }}
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true

      - name: Export digest
        run: |
          echo "${{ steps.build.outputs.digest }}" > digest-${{ matrix.platform }}.txt
        shell: bash

      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digest-${{ matrix.platform }}
          path: digest-${{ matrix.platform }}.txt

  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all digests
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Create multi-platform manifest
        run: |
          digests=$(ls digest-*.txt | xargs cat)
          docker buildx imagetools create --tag ${{ env.REGISTRY_IMAGE }} $digests
